<script>
$(document).ready(function () {

    $('.delete-confrm').on('click', function () {
        return confirm('Are you sure you want to delete this image?');
    });


    <?php if (!empty($this->imageId)) : ?>

    $('a[data-image-id=<?php echo $this->imageId; ?>]').click();

    <?php endif; ?>
});
$(window).load(function () {
    $('#links').collagePlus({
        'targetHeight': 200
    });
});
</script>
<?php
/** @var \Image\Entity\Image[] $images */
$images = $this->images;
/** @var \Zend\Permissions\Acl\AclInterface $acl */
$acl = $this->getHelperPluginManager()->getServiceLocator()->get('acl');
echo $this->flashMessenger()->render('success', array('alert', 'alert-success'));
?>

<div class="modal fade" id="gallery-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body next"></div>
            <div class="modal-footer">
                <div class="row">
                    <div class="col-xs-2">
                        <button type="button" class="btn btn-default pull-left prev"
                            onclick="$.event.trigger({type: 'gallery.go-prev'});">
                            <i class="glyphicon glyphicon-chevron-left"></i>
                            Previous
                        </button>
                    </div>
                    <div class="col-xs-8">
                        <p class="modal-description"></p>
                    </div>
                    <div class="col-xs-2">
                        <button type="button" class="btn btn-primary next"
                                onclick="$.event.trigger({type: 'gallery.go-next'});">
                            Next
                            <i class="glyphicon glyphicon-chevron-right"></i>
                        </button>
                    </div>
                </div>
                <div class="row" id="comments-holder">
                </div>
                <div style="clear: both"></div>
            </div>
        </div>
    </div>
</div>
<div id="links" class="Collage">
   <?php foreach ($images as $image) : ?>

   <img data-image-id="<?php echo $image->getId(); ?>"
       data-description="<?php echo $image->getDescription(); ?>"
       title="<?php echo $image->getTitle();?>"
       src="<?php echo $this->basePath('img/images/'.$image->getImage());?>">

   <?php endforeach; ?>
</div>
