<?php

$this->headScript()
    ->appendFile('//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53df736200219df0');


/** @var \Image\Entity\Image $image */
$image = $this->image;
?>
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53df736200219df0" async="async"></script>
<div>
    <h1><?php echo $this->escapeHtml($image->getAuthor());?></h1>
    <hr>
</div>
<div>
    <div>
    <img class="img-thumbnail image-picture-big"
         src='<?php echo $this->basePath().'/img/images/'.$image->getImage();?>'>
    <div>
    <div class="image-text">
        <p class="description"><?php echo $this->escapeHtml($image->getDescription());?></p> <br><br>
        <p ><?php echo $image->getText();?></p> <br><br>
    </div>
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <div class="addthis_native_toolbox"></div>

</div>