<script>
$(document).ready(function () {
    $('.delete-confrm').on('click', function () {
        return confirm('Are you sure you want to delete this article?');
    });
});
</script>
<?php
/** @var \Article\Entity\Article[] $articles */
$articles = $this->articles;
/** @var \Zend\Permissions\Acl\AclInterface $acl */
$acl = $this->getHelperPluginManager()->getServiceLocator()->get('acl');
echo $this->flashMessenger()->render('success', array('alert', 'alert-success'));

foreach ($articles as $article) :
    ?>

    <article class="row">
        <h2><?php echo $this->escapeHtml($article->getTitle()); ?></h2>
        <hr>
        <div class="col-sm-2">
            <img class="img-thumbnail article-picture"
                 src='<?php echo $this->basePath().'img/articles/'.$article->getImage();?>'>
        </div>
        <div class="col-sm-10">
            <?php echo $this->escapeHtml($article->getDescription()); ?>
            <br><br>
            <a href="<?php echo $this->url('read-article', ['id' => $article->getId()]) ?>"
               class="btn btn-sm btn-primary">
                <i class="glyphicon glyphicon-log-in"></i>
                &nbsp;
                Read more
            </a>
            <?php if ($acl->isAllowed($this->aclRole(), new \Application\Acl\Resource\Article($article), 'modify')) : ?>
                <a href="<?php echo $this->url('update-article', ['id' => $article->getId()]) ?>"
                   class="btn btn-sm btn-primary">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
                <a href="<?php echo $this->url('delete-article', ['id' => $article->getId()]) ?>"
                   class="btn btn-sm btn-danger delete-confrm">
                    <i class="glyphicon glyphicon-trash"></i>
                </a>
            <?php endif; ?>
        </div>

    </article>

<?php
endforeach;