<?php

$this->headScript()
    ->appendFile('//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53df736200219df0');


/** @var \Article\Entity\Article $article */
$article = $this->article;
?>
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53df736200219df0" async="async"></script>
<div>
    <h1><?php echo $this->escapeHtml($article->getTitle());?></h1>
    <hr>
</div>
<div>
    <div>
    <img class="img-thumbnail article-picture-big"
         src='<?php echo $this->basePath().'/img/articles/'.$article->getImage();?>'>
    <div>
    <div class="article-text">
        <p class="description"><?php echo $this->escapeHtml($article->getDescription());?></p> <br><br>
        <p ><?php echo $article->getText();?></p> <br><br>
    </div>
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <div class="addthis_native_toolbox"></div>

</div>