<?php echo $this->doctype();
$auth = $this->getHelperPluginManager()->getServiceLocator()->get('auth');
?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('What\'s in your pocket'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet('http://blueimp.github.io/Gallery/css/blueimp-gallery.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-image-gallery.min.css')
        ->appendStylesheet($this->basePath() . '/css/bootstrap-select.min.css')
        ->appendStylesheet($this->basePath() . '/css/triada-style.css')
        ->appendStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->appendStylesheet($this->basePath() . '/css/font-awesome.min.css')
    ; ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/jquery.collagePlus.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap-select.min.js')
        ->prependFile($this->basePath() . '/js/jquery.ajaxchimp.min.js')
        ->prependFile($this->basePath() . '/js/included-plagins.js')
        ->prependFile($this->basePath() . '/js/main.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->appendFile($this->basePath() . '/js/sasquatch-gallery.js'); ?>

</head>
<body>

<header class="site-header">
    <div class="row header-wrap">
        <div class="col-sm-5 header-box">
            <div id="main-menu" class="main-menu">
                <ul>
                    <li>
                        <a href="#about">
							<span class="hidden-xs hidden-sm">
								<i class="hover-label">About</i>
								About
							</span>
							<span class="hidden-md hidden-lg icon">
								<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 25 25" enable-background="new 0 0 25 25" xml:space="preserve" width="25" height="25">
									<path fill="#333333" d="M12.5,25C5.6,25,0,19.4,0,12.5C0,5.6,5.6,0,12.5,0C19.4,0,25,5.6,25,12.5C25,19.4,19.4,25,12.5,25L12.5,25z
									M12.5,0.9C6.1,0.9,0.9,6.1,0.9,12.5c0,6.4,5.2,11.6,11.6,11.6c6.4,0,11.6-5.2,11.6-11.6C24.1,6.1,18.9,0.9,12.5,0.9L12.5,0.9z
									M11.6,20.2V9.3h1.8v10.9H11.6L11.6,20.2z M12.5,7.5c-0.8,0-1.4-0.6-1.4-1.4c0-0.8,0.6-1.4,1.4-1.4c0.8,0,1.4,0.6,1.4,1.4
									C13.9,6.9,13.3,7.5,12.5,7.5L12.5,7.5z"/>
								</svg>
							</span>
                        </a>
                    </li><!--
					--><li>
                        <a href="#contact">
							<span class="hidden-xs hidden-sm">
								<i class="hover-label">Contact</i>
								Contact
							</span>
							<span class="hidden-md hidden-lg icon">
								<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 29 18" enable-background="new 0 0 29 18" xml:space="preserve" width="29" height="18">
									<path fill="#333333" d="M26.4,0H2.6C1.2,0,0,1.2,0,2.6v12.9C0,16.8,1.2,18,2.6,18h23.7c1.5,0,2.6-1.1,2.6-2.6V2.6
									C29,1.2,27.8,0,26.4,0L26.4,0z M26.4,1c0.2,0,0.3,0,0.4,0.1l-12.3,9.5L2.2,1.1C2.3,1.1,2.5,1,2.6,1H26.4L26.4,1z M2.6,17
									c-0.2,0-0.3,0-0.4-0.1l8.4-6.5L9.8,9.7l-8.4,6.5c-0.2-0.2-0.3-0.5-0.3-0.8V2.6c0-0.3,0.1-0.6,0.3-0.8l13.2,10.2L27.7,1.7
									c0.2,0.2,0.3,0.5,0.3,0.8v12.9c0,0.3-0.1,0.6-0.3,0.8l-8.5-6.5l-0.8,0.7l8.4,6.5c-0.1,0-0.3,0.1-0.4,0.1H2.6L2.6,17z"/>
								</svg>
							</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div><!-- .header-box -->

        <div class="col-sm-2 header-box logo-box text-center">
            <a href="index.html"><img src="img/logo.svg" width="68" height="57" alt=""></a>
        </div><!-- .header-box -->

        <div class="col-sm-5 header-box text-right hidden-xs">
            <!-- demonstration - http://keith-wood.name/countdownRef.html -->

        </div><!-- .header-box -->
    </div>
</header><!-- .site-header -->

<input type="hidden"
       value="<?php echo 'http://' . $_SERVER['SERVER_NAME'] . $this->basePath(); ?>"
       id="server_name">
<div id="fb-root"></div>
<script>

    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.3";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
<?php if ($auth->hasIdentity()): ?>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img
                        src="<?php echo $this->basePath('img/zf2-logo.png') ?>"
                        alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('What\'s in your pocket') ?></a>
            </div>
            <div class="collapse navbar-collapse">
                <?php echo $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav'); ?>
            </div>
            <!--/.nav-collapse -->
        </div>
    </nav>
<?php endif; ?>

<div class="container">

    <hr style="margin-top: 35px">

    <?php echo $this->content; ?>

    <hr>

    <footer class="site-footer">
        <div class="container-fluid text-center">
            <div class="copyright">&copy; <?php echo date('Y') ?> by Dessy <?php echo $this->translate('All rights reserved.') ?></div>
            <div class="social">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-google-plus"></i></a>
                <a href="#"><i class="fa fa-behance"></i></a>
            </div>
        </div>
    </footer><!-- .site-footer -->
<!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
