<?php

$this->form->prepare();

echo $this->form()->openTag($this->form);

?>
<h3>Change Password</h3>
<hr>
<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger'));?>
<div class="form-group">
    <?php echo $this->formLabel($form->get('old-password')); ?>
    <div class="col-sm-5">
        <?php echo $this->formElement($form->get('old-password')); ?>
        <?php echo $this->formElementErrors($form->get('old-password')); ?>
    </div>
</div>
<div class="form-group">
    <?php echo $this->formLabel($form->get('new-password')); ?>
    <div class="col-sm-5">
        <?php echo $this->formElement($form->get('new-password')); ?>
        <?php echo $this->formElementErrors($form->get('new-password')); ?>
    </div>
</div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('repeat-new-pass')); ?>
        <div class="col-sm-5">
            <?php echo $this->formElement($form->get('repeat-new-pass')); ?>
            <?php echo $this->formElementErrors($form->get('repeat-new-pass')); ?>
        </div>
    </div>
<div class="form-group">
    <div class="col-sm-5 col-sm-offset-2">
        <?php echo $this->formElement($form->get('button')); ?>
    </div>
</div>
<?php
echo $this->form()->closeTag();