<?php

$this->form->prepare();

echo $this->form()->openTag($this->form);

?>
    <h3>Register</h3>
    <hr>
<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger'));?>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('name')); ?>
        <div class="col-sm-5">
            <?php echo $this->formElement($form->get('name')); ?>
            <?php echo $this->formElementErrors($form->get('name')); ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('email')); ?>
        <div class="col-sm-5">
            <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('password')); ?>
        <div class="col-sm-5">
            <?php echo $this->formElement($form->get('password')); ?>
            <?php echo $this->formElementErrors($form->get('password')); ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('repeat-password')); ?>
        <div class="col-sm-5">
            <?php echo $this->formElement($form->get('repeat-password')); ?>
            <?php echo $this->formElementErrors($form->get('repeat-password')); ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-5 col-sm-offset-2">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>
    </div>
<?php echo $this->formElement($form->get('csrf')); ?>
<?php
echo $this->form()->closeTag();