<section id="about" class="section" style="padding: 100px 0;">
    <div class="section-wrap">
        <div class="section-content">
            <div class="container">
                <h2 class="text-center section-title"
                    data-animation="fadeInDown"
                    data-animation-delay="100"
                    data-out-animation="fadeOutUp"
                    data-out-animation-delay="100">About</h2>

                <div class="row section-description text-center">
                    <div class="col-sm-12 col-md-10 col-md-offset-1">
                        <p class="lead"
                           data-animation="fadeInDown"
                           data-animation-delay="100"
                           data-out-animation="fadeOutUp"
                           data-out-animation-delay="200" style="padding-top: 30px;">
                            This project is dedicated to all small things we carry with us all day, everyday. It might be a tiny note we had for ages, or a ticket that carries the memories of an adventure. It can be anything.</p>
                            <p class="lead">Join the community and share your thoughts, feelings, secrets and beliefs.</p>
                            <p class="lead"><b>SPECIAL THANKS</b> to the author of the short story <a href="https://www.youtube.com/watch?v=6qrwwM1Hgwk" style="text-decoration: none;">“What Do We Have In Our Pokets”</a> <a href="https://www.facebook.com/EtgarKeretOfficial?fref=ts" style="text-decoration: none;">Etgar Keret</a> that was an inspiration for this project.</p>
                    </div>
                </div>


            </div>
        </div><!-- .section-content -->
    </div><!-- .section-wrap -->
</section><!-- #about.section -->