<section id="contact" class="section" style="padding: 100px 0;>
    <div class="section-wrap">
        <div class="section-content">
            <div class="container">
                <div class="contact-wrap relative">
                    <div class="row">
                        <div class="col-xs-offset-0 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
                            <h2 class="text-center section-title"
                                data-animation="fadeInDown"
                                data-animation-delay="900"
                                data-out-animation="fadeOutUp"
                                data-out-animation-delay="100">Contact</h2>

                            <form class="contact-form" method="post">
                                <div class="row">
                                    <div class="col-sm-6 form-group name">
                                        <input type="text"
                                               class="form-control"
                                               name="name"
                                               placeholder="Name"
                                               data-animation="fadeInLeft"
                                               data-animation-delay="100"
                                               data-out-animation="fadeOutLeft"
                                               data-out-animation-delay="900">
                                    </div>

                                    <div class="col-sm-6 form-group email">
                                        <input type="email"
                                               class="form-control"
                                               name="email"
                                               placeholder="Email"
                                               data-animation="fadeInLeft"
                                               data-animation-delay="100"
                                               data-out-animation="fadeOutLeft"
                                               data-out-animation-delay="900">
                                    </div>
                                </div>

                                <div class="form-group comment">
										<textarea class="form-control"
                                                  name="comment"
                                                  placeholder="Message"
                                                  data-animation="fadeInLeft"
                                                  data-animation-delay="100"
                                                  data-out-animation="fadeOutLeft"
                                                  data-out-animation-delay="900"></textarea>
                                </div>

                                <div class="button-box text-center">
                                    <button type="submit"
                                            data-hover="Send"
                                            class="btn btn-default progress-button btn-submit"
                                            data-animation="fadeInDown"
                                            data-animation-delay="900"
                                            data-out-animation="fadeOutUp"
                                            data-out-animation-delay="100">
                                        <span class="button-label">Send</span>
											<span class="success">
												<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 29 23" enable-background="new 0 0 29 23" xml:space="preserve">
													<polyline fill="#FFFFFF" points="0.3,10.2 1.8,8.8 11.4,19.3 27.4,0.4 28.9,1.7 12.9,20.6 11.5,22.3 9.9,20.6 0.3,10.2 "/>
												</svg>
											</span>
                                        <span class="error"></span>
                                        <span class="progress"></span>
                                    </button>
                                </div>
                            </form>

                            <div class="row">
                                <div class="col-sm-5 col-md-5">
                                    <div class="contacts-box xs-text-center"
                                         data-animation="fadeInDown"
                                         data-animation-delay="1000"
                                         data-out-animation="fadeOutUp"
                                         data-out-animation-delay="100">
                                        <div class="icon">
                                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 15 23" enable-background="new 0 0 15 23" xml:space="preserve" width="15" height="23">
													<path fill="#111111" d="M7.5,0C3.4,0,0,3.4,0,7.6c0,1.7,1.1,4.4,3.3,8.4c1.5,2.8,3.1,5.2,3.1,5.3L7.5,23l1.1-1.7
													c0.1-0.1,1.6-2.4,3.1-5.3c2.2-4,3.3-6.7,3.3-8.4C15,3.4,11.6,0,7.5,0L7.5,0z M7.5,11.5c-2.1,0-3.9-1.8-3.9-3.9
													c0-2.2,1.7-3.9,3.9-3.9c2.1,0,3.9,1.8,3.9,3.9C11.4,9.7,9.6,11.5,7.5,11.5L7.5,11.5z"/>
												</svg>
                                        </div>
                                        <div class="text">
                                            Desislava Pencheva, <br>
                                            Editor-in-Chief</a>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-3 col-md-3">
                                    <div class="contacts-box xs-text-center"
                                         data-animation="fadeInDown"
                                         data-animation-delay="1000"
                                         data-out-animation="fadeOutUp"
                                         data-out-animation-delay="100">
                                        <div class="icon">
                                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 20 21" enable-background="new 0 0 20 21" xml:space="preserve" width="20" height="21">
													<path fill="#111111" d="M1.6,2.1c0.3-0.3,0.8-0.7,1.2-0.9C3.3,0.8,4,1,4.9,1.6c1.2,0.8,2.8,2.6,2.6,4.1c-0.1,0.6-0.4,1.2-1,1.8
													C6,8,5.4,8.4,4.9,8.7l7.4,7.3c0.3-0.5,0.7-1.1,1.2-1.7c0.6-0.6,1.2-0.9,1.8-0.9c1.5-0.1,3.4,1.7,4.2,3c0.5,0.8,0.6,1.4,0.3,1.8
													c-0.3,0.5-0.7,1-1.1,1.4c-2.6,2.6-6.3,1.4-8.1,0.2c-1-0.7-3.4-2.5-5.3-4.4c-2-2-3.5-4-4.3-5.1C0.4,9.1-1.2,4.8,1.6,2.1L1.6,2.1z"/>
												</svg>
                                        </div>
                                        <div class="text">
                                            +447450660055<br>

                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-4">
                                    <div class="contacts-box xs-text-center"
                                         data-animation="fadeInDown"
                                         data-animation-delay="1000"
                                         data-out-animation="fadeOutUp"
                                         data-out-animation-delay="100">
                                        <div class="icon">
                                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 24 16" enable-background="new 0 0 24 16" xml:space="preserve" width="24" height="16">
													<path fill="#111111" d="M12,9.8L1.1,1.3C1.4,1.1,1.8,1,2.2,1h19.6c0.4,0,0.8,0.1,1.1,0.3L12,9.8L12,9.8z M23.6,15.1l-7.7-6l-0.7,0.5
													l7.7,6c-0.3,0.2-0.7,0.3-1.1,0.3H2.2c-0.4,0-0.8-0.1-1.1-0.3l7.7-6.1L8.1,9.1l-7.7,6C0.2,14.8,0,14.3,0,13.9V3.1
													c0-0.5,0.2-0.9,0.4-1.3l11.6,9l11.6-9C23.8,2.2,24,2.7,24,3.1v10.7C24,14.3,23.8,14.8,23.6,15.1L23.6,15.1z"/>
												</svg>
                                        </div>
                                        <div class="text">
                                            dmpencheva@gmail.com<br>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div id="map" class="map-box">
                        <div class="map-wrap">
                            <a href="#" class="close">&times;</a>

                            <div
                                class="map-canvas"
                                data-zoom="6"
                                data-lat="40.748441"
                                data-lng="-73.985664"
                                data-title="Bryant Park"
                                data-content="New York, NY">
                            </div>
                        </div>
                    </div>
                </div><!-- .contact-wrap -->
            </div>
        </div><!-- .section-content -->
    </div><!-- .section-wrap -->
</section><!-- #contact.section -->